# Generated by Django 5.1 on 2024-08-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
    ]
