# Generated by Django 5.1 on 2024-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_car_is_crashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
