# Generated by Django 5.1 on 2024-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_user_address_user_city_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CP',
            field=models.CharField(default=28015, max_length=5),
            preserve_default=False,
        ),
    ]
