# Generated by Django 5.0.6 on 2024-08-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_isused_listing_isworking_listing_kilometres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
