# Generated by Django 5.0.6 on 2024-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_isstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
