# Generated by Django 5.0.6 on 2024-08-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_starting_bid_bid_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listingBids', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
